# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_df = pd.read_csv("../output_data/cities.csv")
weather_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Tuktoyaktuk,5,CA,1586382256,65,69.45,-133.04,8.60,12.75
1,Hithadhoo,84,MV,1586382256,68,-0.60,73.08,84.83,10.27
2,Mataura,100,NZ,1586382256,88,-46.19,168.86,52.00,17.00
3,Grindavik,75,IS,1586382256,83,63.84,-22.43,33.80,2.24
4,Bredasdorp,30,ZA,1586382257,77,-34.53,20.04,60.01,11.41

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
weather_df.dtypes

City           object
Cloudiness      int64
Country        object
Date            int64
Humidity        int64
Lat           float64
Lng           float64
Max Temp      float64
Wind Speed    float64
dtype: object

In [4]:
# Store latitude and longtitude in locations
locations = weather_df[["Lat","Lng"]]
# Convert humidity to float
humidity = weather_df["Humidity"].astype(float)
max_humidity = humidity.max()

In [5]:
# Access maps with unique API key
gmaps.configure(api_key=g_key)
# Plot Heatmap
fig = gmaps.figure()
# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max_humidity,
                                 point_radius=3)
# Add layer
fig.add_layer(heat_layer)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
# Narrow the cities weather with temperature between 70 and 80
# Wind speed below 10mph and cloudiness is 0
weather_criteria = weather_df.loc[((weather_df["Max Temp"]>70) & (weather_df["Max Temp"]<80) &
                                 (weather_df["Wind Speed"]<10)) & (weather_df["Cloudiness"]==0),:]
# Drop null values
weather_criteria = weather_criteria.dropna(how='any')
# Reset the index
weather_criteria.reset_index(inplace=True)
# Drop the old index
del weather_criteria["index"]
weather_criteria

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Tura,0,IN,1586382273,48,25.52,90.22,72.32,5.70
1,Jardim,0,BR,1586382280,55,-21.48,-56.14,74.19,4.25
2,Ancud,0,CL,1586382284,40,-41.87,-73.82,71.60,8.05
3,Kang,0,BW,1586382286,20,-23.68,22.79,70.14,6.98
4,Marzuq,0,YE,1586382302,25,14.40,46.47,73.58,4.27
5,Porbandar,0,IN,1586382337,86,21.64,69.61,76.01,9.19
6,Bhādāsar,0,IN,1586382367,25,28.28,74.32,76.87,7.36
7,Benguela,0,AO,1586382369,78,-12.58,13.41,77.14,2.33
8,Dakar,0,SN,1586382362,73,14.69,-17.44,75.20,9.17
9,Najrān,0,SA,1586382375,22,17.49,44.13,75.20,3.47
10,Nokha,0,IN,1586382384,22,27.60,73.42,77.40,8.21
11,Turbat,0,PK,1586382386,41,26.00,63.04,78.87,2.01

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
# Set the narrow country dataframe with new name hotel_df
hotel_df = weather_criteria
# Create a empty column for Hotel Name in the DataFrame
hotel_df["Hotel Name"] = ""
# Loop through every row to access the city name
for i in range(len(hotel_df)):
    # Get the latitude and longitude corresponding to city name
    lat = hotel_df.loc[i]["Lat"]
    lng = hotel_df.loc[i]["Lng"]
    # Create the params to hold searching requirements
    params = {
        "location":f"{lat},{lng}",
        "types":"lodging",
        "radius":5000,
        "key":g_key
    }
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    hotel_json = requests.get(base_url,params).json()
    results = hotel_json['results']
    # Append the hotel name to the DataFrame
    try:
        hotel_df.loc[i,'Hotel Name'] = results[0]['name']
    except:
        hotel_df.loc[i,'Hotel Name'] = " "
# Drop empty list
hotel_df = hotel_df.dropna(how = "any")
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,Tura,0,IN,1586382273,48,25.52,90.22,72.32,5.70,Hotel RIKMAN Continental
1,Jardim,0,BR,1586382280,55,-21.48,-56.14,74.19,4.25,Hotel Estância
2,Ancud,0,CL,1586382284,40,-41.87,-73.82,71.60,8.05,HOTEL ANCUD DON LUCAS
3,Kang,0,BW,1586382286,20,-23.68,22.79,70.14,6.98,Kang Ultra Stop
4,Marzuq,0,YE,1586382302,25,14.40,46.47,73.58,4.27,
5,Porbandar,0,IN,1586382337,86,21.64,69.61,76.01,9.19,Lords Inn Porbandar
6,Bhādāsar,0,IN,1586382367,25,28.28,74.32,76.87,7.36,OMPRAKASH JAKHAR
7,Benguela,0,AO,1586382369,78,-12.58,13.41,77.14,2.33,Hotel Praia Morena
8,Dakar,0,SN,1586382362,73,14.69,-17.44,75.20,9.17,Novotel Dakar
9,Najrān,0,SA,1586382375,22,17.49,44.13,75.20,3.47,محمد هادي ال فطيح
10,Nokha,0,IN,1586382384,22,27.60,73.42,77.40,8.21,Fauji hotel and Restaurant9636024676
11,Turbat,0,PK,1586382386,41,26.00,63.04,78.87,2.01,BOQ's

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in weather_criteria.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# Display Map
fig

Figure(layout=FigureLayout(height='420px'))